from typing import Dict, Any, List

AGRICULTURAL_DISCLAIMER = (
    "NOTICE: Predictions and agricultural guidance generated by this platform are provided "
    "for informational and decision-support purposes only. Recommendations should be verified "
    "by certified local agricultural extension officers, agronomists, or plant pathologists before "
    "applying chemical or biological field treatments."
)

DISEASE_KNOWLEDGE_BASE: Dict[str, Dict[str, Any]] = {
    "Healthy": {
        "disease_name": "Healthy",
        "crop": "Tomato",
        "scientific_name": "Solanum lycopersicum",
        "symptoms": [
            "Vibrant green leaves without spots, lesions, or curling.",
            "Sturdy stems with uniform leaf arrangement.",
            "Normal growth rate without wilting or premature leaf drop."
        ],
        "general_causes": [
            "Optimal soil nutrients, balanced hydration, and proper sunlight exposure."
        ],
        "favorable_conditions": [
            "Well-drained soil (pH 6.0-6.8), 6-8 hours of direct daily sunlight, moderate humidity."
        ],
        "preventive_measures": [
            "Maintain balanced N-P-K fertilization according to soil test recommendations.",
            "Practice drip irrigation to keep foliage dry.",
            "Ensure proper plant spacing (45-60 cm) for air circulation.",
            "Apply organic mulch to maintain root moisture and prevent soil splash."
        ],
        "general_management_practices": [
            "Regular scouting and monitoring for early signs of pests or leaf spots.",
            "Routine pruning of lower sucker leaves to improve airflow near soil line."
        ]
    },
    "Early Blight": {
        "disease_name": "Early Blight",
        "crop": "Tomato",
        "scientific_name": "Alternaria solani",
        "symptoms": [
            "Small dark brown to black spots on older lower leaves first.",
            "Characteristic target-board concentric ring patterns inside leaf lesions.",
            "Yellow halo surrounding brown spots as lesions expand.",
            "Premature defoliation starting from the bottom of the plant upward."
        ],
        "general_causes": [
            "Fungal pathogen Alternaria solani surviving in soil residue and infected plant debris."
        ],
        "favorable_conditions": [
            "Warm temperatures (24°C - 29°C / 75°F - 85°F).",
            "Frequent heavy dew, rainfall, or high relative humidity (>80%).",
            "Prolonged leaf wetness."
        ],
        "preventive_measures": [
            "Implement a 3- to 4-year crop rotation with non-solanaceous crops.",
            "Use disease-certified resistant tomato cultivars when available.",
            "Mulch soil heavily to prevent rain-splash transmission of fungal spores from soil.",
            "Water plants at the base via drip irrigation; avoid overhead sprinklers."
        ],
        "general_management_practices": [
            "Promptly prune and destroy infected lower leaves at first sign of spots.",
            "Clear all crop residue immediately after harvest; do not compost infected material.",
            "Consult local extension services for recommended protective copper-based or bio-fungicide options."
        ]
    },
    "Late Blight": {
        "disease_name": "Late Blight",
        "crop": "Tomato",
        "scientific_name": "Phytophthora infestans",
        "symptoms": [
            "Large, pale green to dark water-soaked irregular spots on leaves.",
            "White, velvety fungal growth on undersides of infected leaves during moist weather.",
            "Dark brown stem lesions that cause stems to collapse rapidly.",
            "Fruit developing firm, dark brown, greasy-looking rot."
        ],
        "general_causes": [
            "Oomycete (water mold) pathogen Phytophthora infestans spread rapidly by wind-blown sporangia."
        ],
        "favorable_conditions": [
            "Cool to moderate temperatures (15°C - 22°C / 60°F - 72°F).",
            "High humidity (>90%) and continuous free leaf moisture (fog, rain, dew)."
        ],
        "preventive_measures": [
            "Plant certified disease-free transplants.",
            "Maximize plant spacing and stake plants vertically to facilitate rapid foliage drying.",
            "Avoid planting tomato crops adjacent to potato fields.",
            "Destroy volunteer tomato and potato plants near field margins."
        ],
        "general_management_practices": [
            "Inspect fields twice weekly during cool, wet weather periods.",
            "Immediately remove and bag severely infected plants to prevent wind dissemination of spores.",
            "Consult certified agronomists for preventative fungicide applications under high-risk weather alerts."
        ]
    },
    "Leaf Mold": {
        "disease_name": "Leaf Mold",
        "crop": "Tomato",
        "scientific_name": "Passalora fulva (syn. Cladosporium fulvum)",
        "symptoms": [
            "Pale green to yellow spots on the upper leaf surface.",
            "Olive-green to dark brown velvety mold growth underneath the corresponding leaf spots.",
            "Infected leaves wither, turn yellow, and drop prematurely.",
            "Blossoms and fruit stems occasionally develop dark rot."
        ],
        "general_causes": [
            "Fungal pathogen Passalora fulva persisting on crop debris and structure surfaces."
        ],
        "favorable_conditions": [
            "High relative humidity (>85%) combined with warm temperatures (20°C - 24°C / 68°F - 75°F).",
            "Common in greenhouse, high-tunnel, or densely shaded field environments with poor ventilation."
        ],
        "preventive_measures": [
            "Select leaf-mold resistant tomato hybrids.",
            "Maintain relative humidity below 85% in greenhouses through ventilation and heating.",
            "Prune lower suckers to maximize light penetration and internal air movement.",
            "Water early in the morning so foliage dries before evening."
        ],
        "general_management_practices": [
            "Remove affected leaves carefully to minimize spore dispersal.",
            "Sanitize greenhouse structures, stakes, and tools between growing cycles.",
            "Apply suitable bio-fungicides or recommended protective sprays upon early diagnosis."
        ]
    },
    "Unclassified/Other Fungal Leaf Spot": {
        "disease_name": "Unclassified/Other Fungal Leaf Spot",
        "crop": "General Crops",
        "scientific_name": "Foliar pathogen (unspecified / uncertain crop)",
        "symptoms": [
            "Foliar discoloration, necrotic lesions, chlorotic halos, or leaf spotting.",
            "Symptoms vary widely across different host plant families and ambient humidity levels.",
            "Premature yellowing or localized leaf tissue senescence."
        ],
        "general_causes": [
            "Foliar fungal or bacterial pathogens thriving under high humidity, poor air circulation, or leaf wetness."
        ],
        "favorable_conditions": [
            "Prolonged leaf surface moisture, overhead watering, high humidity, and poor canopy aeration."
        ],
        "preventive_measures": [
            "Ensure proper plant and row spacing to optimize sunlight penetration and canopy airflow.",
            "Avoid overhead irrigation; water directly at the base early in the day.",
            "Sanitize pruning tools between plants to limit mechanical pathogen transmission.",
            "Practice multi-year crop rotation with unrelated plant families."
        ],
        "general_management_practices": [
            "Remove and safely discard severely spotted or dead leaves.",
            "Maintain soil drainage and avoid working in fields when foliage is wet.",
            "Consult local extension specialists for crop-specific diagnostic verification."
        ]
    }
}


class DiseaseKnowledgeBase:
    """
    Decoupled Agricultural Disease Knowledge Base Provider.
    """
    
    def __init__(self):
        self.kb = DISEASE_KNOWLEDGE_BASE
        self.disclaimer = AGRICULTURAL_DISCLAIMER
        
    def get_disease_info(self, disease_name: str) -> Dict[str, Any]:
        """
        Retrieves detailed structured knowledge for a given disease.
        
        Args:
            disease_name (str): Standardized disease class name or uncertain label.
            
        Returns:
            Dict containing symptoms, causes, favorable conditions, preventive measures,
            management practices, and the professional disclaimer.
        """
        # Map uncertain / mismatch labels to general unclassified entry
        if disease_name.startswith("Uncertain") or disease_name in (
            "Unclassified/Other Fungal Leaf Spot",
            "Unknown",
        ):
            info = self.kb.get("Unclassified/Other Fungal Leaf Spot")
            result = info.copy()
            result["disease_name"] = disease_name
            result["disclaimer"] = self.disclaimer
            return result

        info = self.kb.get(disease_name)
        if info is None:
            # Fallback for unmapped or unknown class
            return {
                "disease_name": disease_name,
                "crop": Config.CROP_NAME,
                "scientific_name": "Unknown",
                "symptoms": ["No specific symptom data available for this class."],
                "general_causes": ["Unknown pathogen."],
                "favorable_conditions": ["Varies."],
                "preventive_measures": ["Consult local agricultural extension for diagnosis."],
                "general_management_practices": ["Consult an agronomist."],
                "disclaimer": self.disclaimer }
            
        result = info.copy()
        result["disclaimer"] = self.disclaimer
        return result

    def get_supported_diseases(self) -> List[str]:
        """Returns list of all supported disease names."""
        return list(self.kb.keys())


_kb_instance = None


def get_knowledge_base() -> DiseaseKnowledgeBase:
    """Singleton getter for DiseaseKnowledgeBase."""
    global _kb_instance
    if _kb_instance is None:
        _kb_instance = DiseaseKnowledgeBase()
    return _kb_instance
